version: '3'
services:
  notification-services:
    ports:
    - "3000:3000"
    image: $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/notification-services:$CIRCLE_TAG
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: $LOG_GROUP
        awslogs-region: us-east-1
        awslogs-stream-prefix: notification-services
  datadog:
    image: datadog/agent:latest
    environment:
     - DD_API_KEY=$DD_API_KEY
     - ECS_FARGATE=true
    logging:
      driver: awslogs
      options:
        awslogs-group: $LOG_GROUP
        awslogs-region: us-east-1
        awslogs-stream-prefix: datadog
