version: '1'
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    cpu_limit: 512
    mem_limit: 1024
  services:
    notification-services:
      essential: true
      mem_limit: '768MB'
    datadog:
      essential: false
      cpu_shares: 128
      mem_limit: '256MB'
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-e5d485cf
      security_groups:
        - sg-d3c64ea4
      assign_public_ip: DISABLED
